vim.g.mapleader = " "
vim.keymap.set("n", "<leader>ee", vim.cmd.Ex)
vim.keymap.set("i", '<A-j>', '<Esc>')
vim.keymap.set("i", '<A-k>', '<Esc>')
vim.keymap.set("v", '<A-k>', '<Esc>')
vim.keymap.set("v", '<A-j>', '<Esc>')
vim.keymap.set("n", '<C-d>', '<C-d>zz')
vim.keymap.set("n", '<C-u>', '<C-u>zz')
vim.keymap.set("n", '<leader>n', vim.cmd.noh)
vim.keymap.set("n", '<C-t>', '<C-e>')
vim.keymap.set("n", '<leader>w', vim.cmd.w)
vim.keymap.set("n", '<leader>w', vim.cmd.w)
vim.api.nvim_set_keymap('x', '<leader>p', '"_dP', { noremap = true, silent = true })
vim.keymap.set('v', '<leader>y', '"+y')
vim.keymap.set("n", 'r', vim.cmd.red)
vim.keymap.set("n", '<leader>q', vim.cmd.q)
vim.keymap.set("v", 'e', '$y')
